# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Y:/Cours/Enseirb-E2/pr214/Ccode/Sources/OLED_rgb_manager/OLED_rgb_manager.cache/wt [current_project]
set_property parent.project_path Y:/Cours/Enseirb-E2/pr214/Ccode/Sources/OLED_rgb_manager/OLED_rgb_manager.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  Y:/Cours/Enseirb-E2/pr214/Ccode/Sources/OLED_rgb_manager/OLED_rgb_manager.srcs/sources_1/new/MEM_init.vhd
  Y:/Cours/Enseirb-E2/pr214/Ccode/Sources/OLED_rgb_manager/OLED_rgb_manager.srcs/sources_1/new/RAM.vhd
  Y:/Cours/Enseirb-E2/pr214/Ccode/Sources/OLED_rgb_manager/OLED_rgb_manager.srcs/sources_1/new/FSM.vhd
  Y:/Cours/Enseirb-E2/pr214/Ccode/Sources/OLED_rgb_manager/OLED_rgb_manager.srcs/sources_1/new/SPI_controller.vhd
  Y:/Cours/Enseirb-E2/pr214/Ccode/Sources/OLED_rgb_manager/OLED_rgb_manager.srcs/sources_1/new/FSM_test.vhd
  Y:/Cours/Enseirb-E2/pr214/Ccode/Sources/OLED_rgb_manager/OLED_rgb_manager.srcs/sources_1/new/top_level_init.vhd
  Y:/Cours/Enseirb-E2/pr214/Ccode/Sources/OLED_rgb_manager/OLED_rgb_manager.srcs/sources_1/new/top_level_test.vhd
}
read_xdc Y:/Cours/Enseirb-E2/pr214/Ccode/Sources/OLED_rgb_manager/OLED_rgb_manager.srcs/constrs_1/new/OLED_rgb_manager_master.xdc
set_property used_in_implementation false [get_files Y:/Cours/Enseirb-E2/pr214/Ccode/Sources/OLED_rgb_manager/OLED_rgb_manager.srcs/constrs_1/new/OLED_rgb_manager_master.xdc]

synth_design -top top_level_test -part xc7a100tcsg324-1
write_checkpoint -noxdef top_level_test.dcp
catch { report_utilization -file top_level_test_utilization_synth.rpt -pb top_level_test_utilization_synth.pb }
